cmd: "npm"
name: "npm build"
args:
    - "run"
    - "build"
sh: true
env:
    NODE_ENV: "development"
atomCommandName: "atom-custom:npmbuild"
targets:
    format:
        cmd: "npm"
        name: "npm format"
        args:
            - "run"
            - "format"
        sh: true
        env:
            NODE_ENV: "development"
        atomCommandName: "atom-custom:npmformat"
    docs:
        cmd: "npm"
        name: "npm docs"
        args:
            - "run"
            - "docs"
        sh: true
        env:
            NODE_ENV: "development"
        atomCommandName: "atom-custom:npmdocs"
