engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: .eslintrc.js
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 200
ratings:
  paths:
    - index.js
    - lib/**/*
    - tasks/**/*
exclude_paths:
  - test/**/*
  - test/*
  - project/**/*
  - project/*
  - docs/**/*
  - docs/*
  - Gruntfile.js
  - .editorconfig
  - .codeclimate.yml
  - LICENSE
  - README.md
  - package.json
  - .*.json
  - .*.yml
  - .*rc
